// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAdOGmyDOC3c2Z9P27MF8XSmq1q--M3Ig',
    appId: '1:512321182467:web:9713a95e0d952f99956736',
    messagingSenderId: '512321182467',
    projectId: 'fir-app-26261',
    authDomain: 'fir-app-26261.firebaseapp.com',
    storageBucket: 'fir-app-26261.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ShjaaBYAMENsHFVR7m_FLgSF10l7CeQ',
    appId: '1:512321182467:android:705ad29da1a71796956736',
    messagingSenderId: '512321182467',
    projectId: 'fir-app-26261',
    storageBucket: 'fir-app-26261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUYXQXzTASJpX1H14FunWulygp_s9KHME',
    appId: '1:512321182467:ios:ec29560135cf7542956736',
    messagingSenderId: '512321182467',
    projectId: 'fir-app-26261',
    storageBucket: 'fir-app-26261.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUYXQXzTASJpX1H14FunWulygp_s9KHME',
    appId: '1:512321182467:ios:ec29560135cf7542956736',
    messagingSenderId: '512321182467',
    projectId: 'fir-app-26261',
    storageBucket: 'fir-app-26261.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAdOGmyDOC3c2Z9P27MF8XSmq1q--M3Ig',
    appId: '1:512321182467:web:d2f82b47254523cb956736',
    messagingSenderId: '512321182467',
    projectId: 'fir-app-26261',
    authDomain: 'fir-app-26261.firebaseapp.com',
    storageBucket: 'fir-app-26261.appspot.com',
  );
}
